---
- name: "Installing fish shell."
  pacman: name=fish state=present
  become: True

- name: "Installing oh-my-fish."
  shell: 'curl -L https://get.oh-my.fish | fish'
  args:
    creates: ~/.local/share/omf
    chdir: /tmp

- name: "Deploying fish configuration file."
  copy:
    src: files/config.fish
    dest: ~/.config/fish/config.fish

- name: "Deploying fish custom functions."
  copy:
    src: files/functions/
    dest: ~/.config/fish/functions/

- name: "Deploying fish custom completions."
  copy:
    src: files/completions/
    dest: ~/.config/fish/completions/

- name: "Deploying oh-my-fish configuration files."
  copy:
    src: files/omf/
    dest: ~/.config/omf/

- name: "Installing oh-my-fish packages."
  shell: 'fish -c "omf install"'
  changed_when: no
