---
- name: "Installing additional cursors."
  packer: name=capitaine-cursors state=present

- name: "Creating .Xresources.d directory."
  file:
    path: ~/.Xresources.d
    state: directory

- name: "Deploying cursors configuration file."
  copy:
    src: files/cursor
    dest: ~/.Xresources.d/cursor

- name: "Initializing cursors configuration in .Xresources."
  lineinfile:
    path: ~/.Xresources
    create: yes
    state: present
    line: '#include ".Xresources.d/cursor"'
