---
- name: "Deploying bash_profile configuration file."
  copy:
    src: files/bashprofile
    dest: ~/.bash_profile

- name: "Deploying bashrc configuration file."
  template:
    src: templates/bashrc.j2
    dest: ~/.bashrc

- name: "Deploying extend.bashrc configuration file."
  copy:
    src: files/extend.bashrc
    dest: ~/.extend.bashrc

- name: "Deploying exports configuration file."
  copy:
    src: files/exports
    dest: ~/.exports

- name: "Deploying aliases configuration file."
  copy:
    src: files/aliases
    dest: ~/.aliases
