---
- hosts: all
  roles:
    - { role: loader, tags: always }
#    - { role: packages, tags: packages }
    - { role: terminator, tags: terminator }
    - { role: zsh, tags: zsh }
    - { role: gpg, tags: gpg }
    - { role: ssh, tags: ssh }
    - { role: git, tags: git }
    - { role: docker, tags: docker }
    - { role: ranger, tags: ranger }
    - { role: sysconfig, tags: sysconfig }
    - { role: topgrade, tags: topgrade }
    - { role: vim, tags: vim }
    - { role: asdf, tags: asdf }
