---
- hosts: all
  roles:
    - { role: loader, tags: always }
    #    - { role: packages, tags: packages }
    - { role: kitty, tags: kitty }
    - { role: zsh, tags: zsh }
    - { role: tmux, tags: tmux }
    - { role: gpg, tags: gpg }
    - { role: ssh, tags: ssh }
    - { role: git, tags: git }
    - { role: docker, tags: docker }
    - { role: ranger, tags: ranger }
    - { role: sysconfig, tags: sysconfig }
    - { role: topgrade, tags: topgrade }
    - { role: neovim, tags: neovim }
    - { role: asdf, tags: asdf }
