---
- hosts: all
  tasks:
    - name: "Limiting the playbooks' execution to Archlinux."
      fail:
        msg: "{{ ansible_distribution }} is not supported by these playbooks!"
      when: ansible_distribution != "Archlinux"

- hosts: all
  roles:
    - { role: loader, tags: always}
    - { role: proxy, tags: proxy }
    # - { role: locale, tags: locale }
    - { role: sysconfig, tags: sysconfig }
    - { role: bash, tags: bash }
    - { role: java, tags: java }
    - { role: zsh, tags: zsh }
    - { role: ssh, tags: ssh }
    - { role: npm, tags: npm }
    - { role: packages, tags: packages }
    - { role: theming, tags: theming }
    - { role: redshift, tags: redshift }
    - { role: i3, tags: i3 }
    - { role: compton, tags: compton }
    - { role: polybar, tags: polybar }
    - { role: rofi, tags: rofi }
    - { role: dunst, tags: dunst }
    - { role: terminator, tags: terminator }
    - { role: ranger, tags: ranger }
    - { role: git, tags: git }
    - { role: docker, tags: docker }
    - { role: vim, tags: vim }
    - { role: maven, tags: maven }
    - { role: vscode, tags: vscode }
    - { role: micro, tags: micro }
    - { role: wlppr, tags: wlppr }
    - { role: emoji, tags: emoji }
