---
all:
  hosts:
    localhost:
      ansible_connection: local

      dotfiles_location: "~/dotfiles"
      local_location: "{{ dotfiles_location }}/local"
      local_configuration: "{{ local_location }}/local.yml"

      user:
        id: "{{ usr.id | default('john_doe') }}"
        name: "{{ usr.name | default('John Doe') }}"
        mail: "{{ usr.mail | default('john@doe.org') }}"
        password: "{{ usr.password | default(omit) }}"
        gpg_key: "{{ usr.gpg_key | default(omit) }}"
        preferences:
          shell: "{{ usr.preferences.shell | default('/usr/bin/zsh') }}"
          xsession: "{{ usr.preferences.xsession | default('i3') }}"
          keymap: "{{ usr.preferences.keymap | default('fr') }}"
          locales: "{{ usr.preferences.locales | default('en_US.UTF-8') }}"
          multiscreen: "{{ usr.preferences.multiscreen | default('false') }}"
          laptop: "{{ usr.preferences.laptop | default('false') }}"

      system:
        proxy:
          enabled: "{{ sys.proxy.enabled | default('false') }}"
          host: "{{ sys.proxy.host | default('') }}"
          port: "{{ sys.proxy.port | default('') }}"
          noproxy: "{{ sys.proxy.noproxy | default ('') }}"
        preferences:
          sudo_nopassword: "{{ sys.preferences.sudo_nopassword | default('yes') }}"
