---
all:
  hosts:
    localhost:
      ansible_connection: local

      dotfiles_location: "~/dotfiles"
      local_location: "{{ dotfiles_location }}/local"
      local_configuration: "{{ local_location }}/local.yml"

      user:
        id: "{{ usr.id | default('john_doe') }}"
        name: "{{ usr.name | default('John Doe') }}"
        mail: "{{ usr.mail | default('john@doe.org') }}"
        password: "{{ usr.password | default(omit) }}"
        gpg_key: "{{ usr.gpg_key | default(omit) }}"
        preferences:
          shell: "{{ usr.preferences.shell | default('/usr/bin/zsh') }}"
          xsession: "{{ usr.preferences.xsession | default('i3') }}"
          keymap: "{{ usr.preferences.keymap | default('fr') }}"
          locales: "{{ usr.preferences.locales | default('en_US.UTF-8') }}"
          multiscreen: "{{ usr.preferences.multiscreen | default('false') }}"

      system:
        proxy:
          enabled: "{{ sys.proxy.enabled | default('false') }}"
          host: "{{ sys.proxy.host | default('') }}"
          port: "{{ sys.proxy.port | default('') }}"
          noproxy: "{{ sys.proxy.noproxy | default ('') }}"
        preferences:
          sudo_nopassword: "{{ sys.preferences.sudo_nopassword | default('yes') }}"

      sys_packages:
        - name: "deps_packer"
          pacman_packages:
            - "jshon" # json parser for shell
            - "expac" # pacman database extraction utility
            - "pygmentize" # python syntax highlighter
        - name: "deps_drivers"
          pacman_packages:
            - "acpi" # kernel modules for acpi (advanced configuration and power interface) parts
            - "alsa-utils" # kernel modules for linux sound architecture
            - "gvfs" # virtual filesystem implementation
        - name: "tools_basics"
          pacman_packages:
            - "curl" # cli for interacting with urls
            - "gnupg" # encryption software
            - "gpa" # gui for gnupg
            - "httpie" # command line http client
            - "jq" # command line json processor
            - "tree" # cli for listing directories in a tree
            - "thefuck" # corrects errors in console commands
            - "yajl" # yet another json library...
            # - "gnome-keyring" # manjaro already has a keyring installed
            - "tldr" # man pages, in a tldr format
            - "fasd" # quick access to files and folders in shell
            - "fd" # user friendly alternative to find
            - "exa" # ls on steroids
            - "xorg-xprop" # property displayer for X
        - name: "tools_terminal"
          pacman_packages:
            - "cowsay" # displays cows in shell
            - "lolcat" # colors shell with rainbow colors
            - "playerctl" # media player controller, lib for spotify
            - "tig" # git lightweight client for shell
            - "w3m" # text based web browser
        - name: "monitoring"
          pacman_packages:
            - "htop" # interactive process viewer
            - "sysstat" # collection of performance monitoring tools

      common_packages:
        - name: "desktop_environment"
          pacman_packages:
            - "xorg-server" # xorg x server
            - "xorg-xinit" # xorg initialisation program
            - "lxappearance-gtk3" # gtk+ theme switcher
            - "xorg-xrdb" # xserver resource database utility
            - "xorg-xfd" # displays all characters in a font using x11 core protocol
        - name: "fonts"
          pacman_packages:
            - "ttf-hack"
            - "ttf-anonymous-pro"
            - "ttf-droid"
            - "ttf-inconsolata"
            - "ttf-liberation"
            - "otf-ipafont"
            - "adobe-source-code-pro-fonts"
          aur_packages:
            - "ttf-font-awesome"
            - "ttf-unifont"
            - "ttf-font-icons"
            - "nerd-fonts-complete"
            - "otf-font-awesome-4"
            - "ttf-ms-fonts"
            - "otf-fira-code-git"
            - "ttf-jetbrains-mono-git"
        - name: "deps_tools"
          pacman_packages:
            - "slop" # select operation program
            - "maim" # screenshot utility
            - "feh" # lightweight image viewer
            - "xclip" # command line interface for clipboard
            - "corkscrew" # ssh tunneling through http proxies
            - "mousepad" # simple text editor for xfce
            - "scrot" # simple command line screenshot utility
            - "dmenu" # generic menu for x
            - "connman" # intel's network connection manager
            - "imagemagick" # image viewing and manipulation program
            # - "archlinux-keyring" # arch pgp keyring # already covered in manjaro
            # - "polkit-gnome" # polkit authentication agent for gnome # already covered in manjaro
          aur_packages:
            # - "gnome-ssh-askpass2" # service for asking passwords # already covered in manjaro
            - "lnav" # tool for viewing and analyzing log files
        - name: "apps"
          pacman_packages:
            - "chromium"
            - "firefox"
            - "keepassxc"
            - "ruby"
            - "filezilla"
            - "gradle"
          aur_packages:
            - "dropbox"
            - "keybase-bin"
            - "spotify"
            - "dbeaver"
          gems:
            - "bundler"
            - "jekyll"
            - "github-pages"
            - "jekyll-gist"
            #- "vivaldi"
            #- "franz-bin"
            #- "pacli"
            #- "ruby-jekyll" # TODO to be moved
            #- "ruby-jekyll-gist" # TODO to be moved
            #- "ruby-jekyll-paginate" # TODO to be moved
            #- "ruby-jekyll-sitemap" # TODO to be moved
            #- "ruby-jekyll-watch" # TODO to be moved
