---
all:
  hosts:
    localhost:
      ansible_connection: local

      dotfiles_location: "~/dotfiles"
      local_location: "{{ dotfiles_location }}/local"
      local_configuration: "{{ local_location }}/local.yml"

      user:
        id: "{{ usr.id | default('antoine') }}"
        name: "{{ usr.name | default('Antoine Neveux') }}"
        mail: "{{ usr.mail | default('antoine@neveux.me') }}"
        password: "{{ usr.password | default(omit) }}"
        gpg_key: "{{ usr.gpg_key | default(omit) }}"

      system:
        proxy:
          enabled: "{{ sys.proxy.enabled | default('false') }}"
          host: "{{ sys.proxy.host | default('') }}"
          port: "{{ sys.proxy.port | default('') }}"
          noproxy: "{{ sys.proxy.noproxy | default ('') }}"
