---
- name: "Installing blueman for managing bluetooth."
  pacman:
    name:
      - blueman
    state: present
  become: True

- name: "Enabling automatic sound switch to connected bluetooth devices."
  lineinfile:
    path: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"
  become: True
