---
- name: "Installing compton."
  aur:
    use: yay
    name:
      - compton-git
    state: present

- name: "Deploying compton configuration file."
  copy:
    src: files/compton.conf
    dest: ~/.config/compton.conf
