---
- name: "Creating tools directory."
  file:
    path: '~/tools'
    state: directory

- name: "Checking if idea has already been installed on the system."
  stat:
    path: '/opt/idea/{{ idea.version }}/bin'
  register: stat_idea_installation_directory

- name: "Downloading IntelliJ IDEA binaries."
  get_url:
    url: 'http://download.jetbrains.com/idea/{{ idea.filename }}'
    dest: '~/tools/{{ idea.filename }}'
    sha256sum: '{{ idea.checksum }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  when: not stat_idea_installation_directory.stat.exists

- name: "Creating IntelliJ IDEA installation directory."
  file:
    dest: '/opt/idea/{{ idea.version }}'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  become: True

- name: "Installing IntelliJ IDEA."
  tags:
    # Suppress: [ANSIBLE0006] tar used in place of unarchive module
    # The unarchive module didn't support `--strip-components` before
    # `extra_opts` was added in 2.1 and we're supporting >= 2.0.
    - skip_ansible_lint
  command: >
    /bin/tar --extract --gunzip --strip-components=1
    --file '/home/{{ user.id }}/tools/{{ idea.filename }}'
    --directory '/opt/idea/{{ idea.version }}'
  args:
    creates: '/opt/idea/{{ idea.version }}/bin'
    # Suppress: [WARNING]: Consider using unarchive module rather than running tar
    warn: no
  become: True

- name: "Linking IntelliJ IDEA runner to executable binaries."
  file:
    src: '/opt/idea/{{ idea.version }}/bin/idea.sh'
    dest: /usr/local/bin/idea
    state: link
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  become: True
