---
- name: "Installing additional cursors."
  aur: name=capitaine-cursors state=present

- name: "Creating .Xresources.d directory."
  file:
    path: ~/.Xresources.d
    state: directory

- name: "Deploying cursors configuration file."
  copy:
    src: files/cursor
    dest: ~/.Xresources.d/cursor

- name: "Initializing cursors configuration in .Xresources.d."
  lineinfile:
    path: ~/.Xresources
    create: yes
    state: present
    line: '#include ".Xresources.d/cursor"'

- name: "Installing numix theme and associated tooling."
  aur:
    name:
      - numix-themes-darkblue
      - vibrancy-colors
    state: present

- name: "Creating gtk configuration directory."
  file:
    path: ~/.config/gtk-3.0/
    state: directory

- name: "Deploying gtk configuration file."
  copy:
    src: files/settings.ini
    dest: ~/.config/gtk-3.0/settings.ini

- name: "Configuring Qt as a GTK theme."
  copy:
    src: files/Trolltech.conf
    dest: ~/.config/Trolltech.conf

- name: "Updating font cache."
  shell: creates=.Xdefaults fc-cache -f
  changed_when: no

- name: "Deploying .Xresources file."
  copy:
    src: files/Xresources
    dest: ~/.Xresources
    backup: yes

- name: "Linking Xresources file to Xdefaults."
  file:
    src: ~/.Xresources
    dest: ~/.Xdefaults
    state: link
    force: yes
