---
- name: "Installing openssh."
  pacman: name=openssh state=present
  become: True

- name: "Creating the configuration folder for ssh."
  file:
    path: ~/.ssh/
    state: directory

- name: "Deploying ssh configuration file."
  copy:
    src: files/config
    dest: ~/.ssh/config
    backup: yes

- name: "Searching for local ssh configuration files."
  stat: path="{{ local_location }}/ssh/config.d"
  register: _ssh_local_configuration

- name: "Deploying local ssh configuration files."
  copy:
    src: "{{ local_location }}/ssh/config.d"
    dest: ~/.ssh/
  when: _ssh_local_configuration.stat.exists
