---
- name: "Installing zsh and associated tooling."
  pacman:
    name:
      - zsh
      - most
      - zsh-syntax-highlighting
    state: present
  become: True

- name: "Installing asdf."
  aur:
    name:
      - asdf
      - asdf-vm
    state: present

- name: "Cloning prezto for installation."
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto
    recursive: yes
    update: no

- name: "Searching for zsh-syntax-highlighting script."
  shell: find /usr -name zsh-syntax-highlighting.zsh 2>/dev/null
  become: True
  check_mode: no
  register: zsh_syntax_highlighting_dir
  changed_when: no

- name: "Creating zsh configuration directories."
  file: path={{item}} state=directory
  with_items:
    - ~/.zfunctions
    - ~/.zsh
    - ~/.zshrc.d

- name: "Deploying zsh additional configuration files."
  copy:
    src: files/zshrc.d/
    dest: ~/.zshrc.d/

- name: "Deploying custom zsh functions."
  copy:
    src: files/zfunctions/
    dest: ~/.zfunctions/

- name: "Cloning zsh-ausuggestions for installation."
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/zsh-autosuggestions

- name: "Linking zprezto login configuration."
  file:
    src: ~/.zprezto/runcoms/zlogin
    dest: ~/.zlogin
    state: link

- name: "Linking zprezto logout configuration."
  file:
    src: ~/.zprezto/runcoms/zlogout
    dest: ~/.zlogout
    state: link

- name: "Linking zprezto profile configuration."
  file:
    src: ~/.zprezto/runcoms/zprofile
    dest: ~/.zprofile
    state: link

- name: "Linking zprezto env configuration."
  file:
    src: ~/.zprezto/runcoms/zshenv
    dest: ~/.zshenv
    state: link

- name: "Deploying zpreztorc configuration file."
  copy:
    src: files/zpreztorc
    dest: ~/.zpreztorc

- name: "Deploying p10k recommended fonts."
  copy:
    src: files/fonts/
    dest: /usr/share/fonts/TTF/
  become: True

- name: "Deploying p10k configuration."
  copy:
    src: files/p10k.zsh
    dest: ~/.p10k.zsh

- name: "Searching for local zsh scripts."
  stat: path="{{ local_location }}/zsh/zshrcd"
  register: _zsh_local_scripts

- name: "Deploying local zsh scripts."
  copy:
    src: "{{ local_location }}/zsh/zshrcd/"
    dest: ~/.zshrc.d/
  when: _zsh_local_scripts.stat.exists

- name: "Deploying zsh configuration file."
  vars:
    additional_local_config: '{{lookup("file", vars["local_location"] + "/zsh/config") }}'
  template:
    src: templates/zshrc.j2
    dest: ~/.zshrc
    backup: True
