---
- name: "Installing termite and associated tooling."
  pacman: name={{item}} state=present
  with_items:
    - termite
    - termite-terminfo
  become: True

- name: "Creating termite configuration directory."
  file:
    path: ~/.config/termite
    state: directory

- name: "Deploying termite configuration file."
  copy:
    src: files/config
    dest: ~/.config/termite/config
    backup: yes

- name: "Deploying gtk css for having padding in termite."
  copy:
    src: files/gtk.css
    dest: ~/.config/gtk-3.0/
