---
- name: "Installing numix theme and associated tooling."
  packer: name={{item}} state=present
  with_items:
    - numix-themes-darkblue
    - vibrancy-colors

- name: "Creating gtk configuration directory."
  file:
    path: ~/.config/gtk-3.0/
    state: directory

- name: "Deploying gtk configuration file."
  copy:
    src: files/settings.ini
    dest: ~/.config/gtk-3.0/settings.ini

- name: "Configuring Qt as a GTK theme."
  copy:
    src: files/Trolltech.conf
    dest: ~/.config/Trolltech.conf

- name: "Updating font cache."
  shell: creates=.Xdefaults fc-cache -f
  changed_when: no

- name: "Linking Xresources file to Xdefaults."
  file:
    src: ~/.Xresources
    dest: ~/.Xdefaults
    state: link
    force: yes
