---
# Note that I'm actually using i3-gaps, a fork of i3wm.
# That is because I like fancy gaps around windows.
- name: "Installing i3-gaps and theming dependencies."
  aur:
    use: yay
    name:
      - git
      - rofi
      - python-pip
      - ttf-font-awesome
      - adobe-source-code-pro-fonts
      - binutils
      - gcc
      - make
      - pkg-config
      - fakeroot
      - python-yaml
      - nerd-fonts-complete
      - feh
      - gsimplecal
      - xdotool
      - playerctl
      - wireless_tools
      - tk
      - github-cli
    state: present

- name: "Installing i3-gaps and associated tooling."
  aur:
    use: yay
    name:
      - i3-gaps
      - i3blocks
      - i3lock-color
      - xautolock
      - rofi
      - ffcast
      - slop
      - xclip
    state: present

- name: "Deploying xinitrc configuration file."
  copy:
    src: files/xinitrc
    dest: ~/.xinitrc
    backup: yes

- name: "Creating the configuration folder for i3."
  file:
    path: ~/.i3/
    state: directory

- name: "Creating i3blocks configuration directory."
  file:
    path: ~/.config/i3blocks/
    state: directory

- name: "Creating i3blocks scripts directory."
  file:
    path: ~/.config/i3blocks/scripts/
    state: directory

- name: "Copying i3blocks scripts in configuration directory."
  copy:
    src: files/scripts/
    dest: ~/.config/i3blocks/scripts/
    mode: 0755

- name: "Deploying i3blocks configuration file."
  copy:
    src: files/i3blocks.conf
    dest: ~/.config/i3blocks/config

- name: "Deploying i3blocks minimal configuration file."
  copy:
    src: files/i3blocks-minimal.conf
    dest: ~/.config/i3blocks/config-minimal

- name: "Copying i3lock script."
  copy:
    src: files/lock.sh
    dest: ~/.i3/lock.sh
    mode: 0755

- name: "Copying search script."
  copy:
    src: files/search.sh
    dest: ~/.i3/search.sh
    mode: 0755

- name: "Copying screenshot script."
  copy:
    src: files/screenshot.sh
    dest: ~/.i3/screenshot.sh
    mode: 0755

- name: "Searching for local i3 scripts."
  stat: path="{{ local_location }}/i3/scripts"
  register: _i3_local_scripts

- name: "Deploying local i3 scripts."
  copy:
    src: "{{ local_location }}/i3/scripts/"
    dest: ~/.i3/
  when: _i3_local_scripts.stat.exists

- name: "Deploying i3 main configuration file."
  vars:
    additional_local_config: '{{lookup("file", vars["local_location"] + "/i3/config") }}'
  template:
    src: templates/config.j2
    dest: ~/.i3/config
    backup: True
