---
- name: "Installing git and associated tooling."
  aur:
    use: yay
    name:
      - git
      - diff-so-fancy
      - kdiff3
      - git-secrets
    state: present

- name: "Deploying a global gitignore file."
  copy:
    src: files/gitignore
    dest: ~/.gitignore

- name: "Deploying a global gitattributes file."
  copy:
    src: files/gitattributes
    dest: ~/.gitattributes

- name: "Deploying git configuration file."
  vars:
    additional_local_config: '{{lookup("file", vars["local_location"] + "/git/config") }}'
  template:
    src: templates/gitconfig.j2
    dest: ~/.gitconfig
    backup: yes
