---
- name: "Installing git and associated tooling."
  aur:
    use: yay
    name:
      - git
      - diff-so-fancy
      - kdiff3
      - git-secrets
    state: present

- name: "Deploying a global gitignore file."
  copy:
    src: files/gitignore
    dest: ~/.gitignore

- name: "Deploying a global gitattributes file."
  copy:
    src: files/gitattributes
    dest: ~/.gitattributes

- name: "Deploying a global commit template file."
  copy:
    src: files/gitmessage
    dest: ~/.gitmessage

- name: "Searching for local git hooks."
  stat: path="{{ local_location }}/git/hooks"
  register: _git_local_hooks

- name: "Creating global git hooks directory."
  file:
    path: ~/.githooks/
    state: directory
  when: _git_local_hooks

- name: "Deploying local git hooks."
  copy:
    src: "{{ local_location }}/git/hooks/"
    dest: ~/.githooks/
    mode: 0755
  when: _git_local_hooks

- name: "Deploying git configuration file."
  vars:
    additional_local_config: '{{lookup("file", vars["local_location"] + "/git/config") }}'
  template:
    src: templates/gitconfig.j2
    dest: ~/.gitconfig
    backup: yes
