---
- name: "Installing atom."
  pacman: name=atom state=present
  become: True

- name: "Creating atom's configuration directory."
  file:
    path: ~/.atom
    state: directory

- name: "Deploying atom package manager configuration file (.apmrc)."
  template:
    src: templates/apmrc.j2
    dest: ~/.atom/.apmrc

- name: "Installing atom packages."
  shell: >
    apm list --bare | grep -E '^{{ item }}@'
    && echo 'Already installed.'
    || apm install '{{ item }}'
  with_items:
    - "{{ atom_packages }}"
  loop_control:
    label: "[{{ item }}]"
  register: apm_result
  changed_when: "'Already installed.' not in apm_result.stdout"

- name: "Deploying custom atom keymap."
  copy:
    src: files/keymap.cson
    dest: ~/.atom/keymap.cson
    backup: yes

- name: "Deploying custom atom configuration."
  copy:
    src: files/config.cson
    dest: ~/.atom/config.cson
    backup: yes
