---
- name: "Installing polybar tools dependencies."
  pacman: name=wireless_tools state=present
  become: True

- name: "Installing polybar and associated tooling."
  aur: name=polybar-git state=present

- name: "Creating polybar configuration directory"
  file:
    path: ~/.config/polybar
    state: directory

- name: "Deploying polybar custom configuration files."
  copy:
    src: files/
    dest: ~/.config/polybar/
    mode: 0755
