---
- name: "Installing polybar."
  aur:
    name:
      - polybar-git
      - pulseaudio-control
    state: present

- name: "Installing polybar fonts."
  copy:
    src: files/fonts/
    dest: ~/.local/share/fonts

- name: "Refreshing fonts cache."
  shell: fc-cache -f
  changed_when: no

- name: "Creating polybar configuration directory."
  file:
    path: ~/.config/polybar/
    state: directory

- name: "Creating polybar scripts directory."
  file:
    path: ~/.config/polybar/scripts/
    state: directory

- name: "Deploying polybar configuration files."
  copy:
    src: files/configuration/
    dest: ~/.config/polybar/

- name: "Deploying polybar scripts files."
  copy:
    src: files/scripts/
    dest: ~/.config/polybar/scripts/
    mode: 0755

- name: "Deploying polybar execution script."
  copy:
    src: files/polybar.sh
    dest: ~/.config/polybar/polybar.sh
    mode: 0755
