---
- name: "Installing JDKs."
  pacman:
    name:
      - jdk8-openjdk
      - openjdk8-doc
      - openjdk8-src
      - jdk11-openjdk
      - openjdk11-doc
      - openjdk11-src
      - jdk-openjdk
      - openjdk-doc
      - openjdk-src
    state: present
  become: True

- name: "Installing GraalVM."
  aur:
    use: yay
    name:
      - jdk11-graalvm-bin
      - native-image-jdk11-bin
      - jdk8-graalvm-bin
      - native-image-jdk8-bin
    state: present
