---
# Dealing with emoji on Linux, thanks a lot to:
# https://pat-s.me/post/emoji-support-for-notion-so-on-linux/

- name: "Installing fonts allowing emojis."
  pacman:
    name:
      - ttf-liberation
      - noto-fonts
      - noto-fonts-emoji
      - powerline-fonts
    state: present
  become: True

- name: "Deploying emoji font configuration file."
  copy:
    src: files/local.conf
    dest: /etc/fonts/local.conf
    backup: no
  become: True
