---
- name: "Installing rofi."
  aur:
    name:
      - rofi
      - rofimoji
      - xdotool
      - xclip
      - xsel
      - mpd
      - mpc
      - scrot
    state: present

- name: "Installing rofi fonts."
  copy:
    src: files/fonts/
    dest: ~/.local/share/fonts

- name: "Creating rofi configuration directory."
  file:
    path: ~/.config/rofi
    state: directory

- name: "Deploying rofi main configuration file."
  copy:
    src: files/configuration/default.rasi
    dest: ~/.config/rofi/config.rasi

- name: "Deploying rofi fuzzy configuration file."
  copy:
    src: files/configuration/fuzzy.rasi
    dest: ~/.config/rofi/config-fuzzy.rasi

- name: "Deploying rofimoji configuration file."
  copy:
    src: files/rofimoji/rofimoji.rc
    dest: ~/.config/rofimoji.rc

- name: "Deploying rofimoji theme file."
  copy:
    src: files/rofimoji/rofimoji-theme.rasi
    dest: ~/.config/rofi/rofimoji-theme.rasi

- name: "Deploying rofi themes."
  copy:
    src: files/themes/
    dest: ~/.config/rofi/

- name: "Deploying powermenu."
  copy:
    src: files/powermenu.sh
    dest: ~/.config/rofi/powermenu.sh
    mode: 0755

- name: "Creating rofi music configuration directory."
  file:
    path: ~/.config/rofi/music
    state: directory

- name: "Deploying rofi music files."
  copy:
    src: files/music/
    dest: ~/.config/rofi/music/
    mode: 0755
