---
- name: "Installing rofi fonts."
  copy:
    src: files/fonts/
    dest: ~/.local/share/fonts

- name: "Creating rofi configuration directory."
  file:
    path: ~/.config/rofi
    state: directory

- name: "Deploying rofi main configuration file."
  copy:
    src: files/configuration/config.rasi
    dest: ~/.config/rofi/config.rasi

- name: "Deploying rofi themes."
  copy:
    src: files/themes/
    dest: ~/.config/rofi/

- name: "Deploying powermenu."
  copy:
    src: files/powermenu.sh
    dest: ~/.config/rofi/powermenu.sh
    mode: 0755

- name: "Creating rofi music configuration directory."
  file:
    path: ~/.config/rofi/music
    state: directory

- name: "Deploying rofi music files."
  copy:
    src: files/music/
    dest: ~/.config/rofi/music/
    mode: 0755
