---
- name: "Installing rofi."
  aur:
    name:
      - rofi
      - rofimoji
      - xdotool
      - xclip
      - xsel
    state: present

- name: "Creating rofi configuration directory."
  file:
    path: ~/.config/rofi
    state: directory

- name: "Creating rofi themes directory."
  file:
    path: ~/.config/rofi/themes
    state: directory

- name: "Deploying rofi configuration file."
  copy:
    src: files/config.rasi
    dest: ~/.config/rofi/config.rasi

- name: "Deploying rofi slate theme configuration file."
  copy:
    src: files/slate.rasi
    dest: ~/.config/rofi/themes/slate.rasi
