---
- name: "Installing rofi."
  aur: name=rofi state=present

- name: "Creating rofi configuration directory."
  file:
    path: ~/.config/rofi
    state: directory

- name: "Creating .Xresources.d configuration directory."
  file:
    path: ~/.Xresources.d
    state: directory

- name: "Deploying rofi configuration file."
  copy:
    src: files/rofi
    dest: ~/.Xresources.d/rofi

- name: "Initializing rofi from Xresources configuration file."
  lineinfile:
    path: ~/.Xresources
    create: yes
    state: present
    line: '#include ".Xresources.d/rofi"'
