---
- name: "Installing rofi."
  aur:
    name:
      - rofi
      - rofimoji
      - xdotool
      - xclip
      - xsel
    state: present

- name: "Creating rofi configuration directory."
  file:
    path: ~/.config/rofi
    state: directory

- name: "Deploying rofi configuration files."
  copy:
    src: files/
    dest: ~/.config/rofi/

- name: "Deploying rofimoji configuration file."
  copy:
    src: files/rofimoji.rc
    dest: ~/.config/rofimoji.rc
