---
- name: "Installing system packages."
  pacman:
    name: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ sys_packages | selectattr('pacman_packages', 'defined') | list }}"
    - pacman_packages
  when: item.0.when | default(True)
  loop_control:
    label: "[{{ item.0.name }}] {{ item.1 }}"
  become: True

- name: "Installing cower (AUR agent)."
  shell: curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=cower; makepkg PKGBUILD --skippgpcheck --install --needed --noconfirm
  args:
    creates: /usr/bin/cower
    chdir: /tmp

- name: "Installing packer (pacman + AUR wrapper)."
  shell: curl -o PKGBUILD https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=packer-git; makepkg PKGBUILD --install --needed --noconfirm
  args:
    creates: /usr/bin/packer
    chdir: /tmp
