---
- name: "Installing lightdm."
  pacman: name=lightdm state=present
  become: True

- name: "Creating the system autologin group."
  group:
    name: autologin
    system: yes
    state: present
  become: True

- name: "Configuring lightdm autologin user."
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    state: present
    insertafter: "^{{ '[Seat:*]' | regex_escape() }}"
    regexp: ^#?autologin-user=
    line: "autologin-user={{ user.id }}"
  become: True

- name: "Configuring lightdm autologin session."
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    state: present
    insertafter: "^{{ '[Seat:*]' | regex_escape() }}"
    regexp: ^#?autologin-session=
    line: "autologin-session={{ user.preferences.xsession }}"
  become: True

- name: "Appending autologin group the the main user."
  user:
    name: "{{ user.id }}"
    groups:
      - autologin
    append: yes
  become: True

- name: "Enabling the lightdm service."
  service:
    name: "lightdm.service"
    enabled: "yes"
  become: True
