#!/bin/bash

#                    /)
#           /\___/\ ((
#           \`@_@'/  ))
#           {_:Y:.}_//
# ----------{_}^-'{_}-------------------------
# Few basic exports I want in bash.
#

# Make vim as default editor
export EDITOR='vim'

# Set some default java options
export JAVA_OPTS='-Xms128m -Xmx256m'

# Helpers/Reminders for docker hosts
export DOCKER_DEFAULT=tcp://127.0.0.1:2375
export DOCKER_HOST=$DOCKER_DEFAULT

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'
