#!/bin/bash

#                    /)
#           /\___/\ ((
#           \`@_@'/  ))
#           {_:Y:.}_//
# ----------{_}^-'{_}-------------------------
# Few basic exports I want in bash.
#

# Make vim as default editor
export EDITOR='vim'

# Set some default java options
export JAVA_OPTS='-Xms128m -Xmx256m'

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X'
