---
- name: "Installing docker and associated tooling."
  pacman:
    name:
      - docker
      - ctop
    state: present
  become: True
  when: ansible_distribution == "Archlinux"

- name: "Creating group docker."
  group:
    name: docker
    state: present
  become: True

- name: "Adding current user to docker group."
  user:
    name: "{{ user.id }}"
    groups: docker
    append: true
  become: True

- name: "Enabling the docker service by default."
  service:
    name: "docker.service"
    enabled: "yes"
  become: True
