# Using oh-my-zsh

export ZSH=~/.oh-my-zsh

# Loading personal preferences

[[ -f ~/.me ]] && source ~/.me

# Settings for powerlevel9k

DEFAULT_USER=$ME
[[ -f ~/.powerlevel9k  ]] && source ~/.powerlevel9k
ZSH_THEME="powerlevel9k/powerlevel9k"

# zsh settings

ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

# Loading personal aliases and exports

[[ -f ~/.aliases ]] && source ~/.aliases
[[ -f ~/.exports ]] && source ~/.exports

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!

export SDKMAN_DIR=~/.sdkman
[[ -s $SDKMAN_DIR/bin/sdkman-init.sh ]] && source $SDKMAN_DIR/bin/sdkman-init.sh
