---
- name: "Installing vim and associated tooling."
  pacman:
    name:
      - vim
      - editorconfig-core-c
    state: present
  become: True

- name: "Installing from pacman additional code formatters."
  pacman: name=astyle state=present
  become: True

- name: "Installing from pip additional code formatters."
  pip:
    name: yapf
    state: latest
    extra_args: --user

- name: "Creating vim configuration directories."
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle
    - ~/.vim/autoload
    - ~/.vim/colors

- name: "Deploying vim configuration file."
  copy:
    src: files/vimrc
    dest: ~/.vimrc

- name: "Setting up Vundle."
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: ~/.vim/bundle/Vundle.vim
  changed_when: no

- name: "Installing vim plugins through Vundle."
  shell: vim +PluginInstall +qall
  changed_when: no

- name: "Updating vim plugins through Vundle."
  shell: vim +PluginUpdate +qall
  changed_when: no

- name: "Installing YouCompleteMe scripts."
  shell: cd ~/.vim/bundle/YouCompleteMe && ./install.py
  changed_when: no
