---
- name: "Installing vim and associated tooling."
  pacman: name={{item}} state=present
  with_items:
    - vim
  become: True

- name: "Creating vim configuration directories."
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - ~/.vim
    - ~/.vim/bundle
    - ~/.vim/autoload
    - ~/.vim/colors

- name: "Deploying vim-atomified colorscheme."
  copy:
    src: files/atomified.vim
    dest: ~/.vim/colors/atomified.vim

- name: "Deploying vim configuration file."
  copy:
    src: files/vimrc
    dest: ~/.vimrc

- name: "Setting up Vundle."
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: ~/.vim/bundle/Vundle.vim
  changed_when: no

- name: "Installing vim plugins through Vundle."
  shell: vim +PluginInstall +qall
  changed_when: no
