---
- name: "Installing GPG and required tools."
  pacman:
    name:
      - gnupg
      - hopenpgp-tools
      - pcsclite
      - ccid
      - yubikey-personalization
      - yubikey-manager
      - rng-tools
      - yubioath-desktop
    state: present
  become: True

- name: "Installing Yubikey tools."
  aur:
    name:
      - yubioath-desktop
    state: present

- name: "Creating the configuration folder for gpg."
  file:
    path: ~/.gnupg
    state: directory

- name: "Deploying GPG configuration."
  copy:
    src: files/gpg.conf
    dest: ~/.gnupg/gpg.conf

- name: "Deploying GPG Agent configuration."
  copy:
    src: files/gpg-agent.conf
    dest: ~/.gnupg/gpg-agent.conf