#!/bin/bash

# Easy navigation

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias -- -='cd -'

alias open='exo-open'

# Folder Shortcuts

alias d='cd ~/Dropbox'
alias dl='cd ~/Downloads'
alias dt='cd ~/Desktop'
alias g='cd ~/git'
alias tools='cd ~/tools'

# LS Colors

export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# ls tweaks

alias l='ls -lF --color=auto'
alias la='ls -laF --color=auto'
alias ls='ls -l --color=auto'
alias ll='ls -Al --color=auto'

# grep tweaks

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# System helpers

alias update='chmod +x ~/.manjaro_update.sh && ~/.manjaro_update.sh'
alias unlock_pacman='sudo rm /var/lib/pacman/db.lck'

# Tools Shortcuts

alias vi='vim'
eval $(thefuck --alias)
alias subl='~/tools/sublime_text_3/sublime_text'
alias compose='docker-compose'

alias pacman='sudo -E pacman'
alias systemctl='sudo -E systemctl'

# Git tweaks

alias status='git status'
alias log='git log --oneline --all --graph --decorate $*'

# Daemons / Agents

alias start_ssh='eval `ssh-agent -s`;ssh-add ~/.ssh/id_rsa'
alias start_docker='sudo systemctl start docker.service'

# Helpful commands

alias path='echo -e ${PATH//:/\\n}'
