return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "bash-debug-adapter",
        "bash-language-server",
        "beautysh",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "editorconfig-checker",
        "flake8",
        "jq",
        "json-lsp",
        "lua-language-server",
        "luacheck",
        "luaformatter",
        "markdownlint",
        "shellcheck",
        "shellharden",
        "shfmt",
        "stylua",
        "vim-language-server",
        "yaml-language-server",
      },
    },
  },
}
